# This software is contributed or developed by KYOCERA Corporation.
# (C) 2018 KYOCERA Corporation
#
# Makefile for thre fingerprint drivers
#

obj-$(CONFIG_INPUT_FINGERPRINT_FPC1020)	+= fpc1020_platform_tee.o
