# This software is contributed or developed by KYOCERA Corporation.
# (C) 2020 KYOCERA Corporation
#

obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_OEM_HKADC)		+= oem/
