# This software is contributed or developed by KYOCERA Corporation.
# (C) 2018 KYOCERA Corporation
#
# Makefile for thre fingerprint drivers
#

obj-$(CONFIG_INPUT_FINGERPRINT_FPC) += fpc/
obj-$(CONFIG_INPUT_FINGERPRINT_CANVASBIO_TSUBAKI02) += canvasbio/TSUBAKI02/
obj-$(CONFIG_INPUT_FINGERPRINT_CANVASBIO_TSUBAKI03) += canvasbio/TSUBAKI03/
obj-y += egis/
