# This software is contributed or developed by KYOCERA Corporation.
# (C) 2019 KYOCERA Corporation
#
# Makefile for the fingerprint drivers.
#

obj-$(CONFIG_CANVASBIO_FINGERPRINT) += cbfp.o
obj-$(CONFIG_CANVASBIO_FINGERPRINT_NAVIGATION) += cb_navi.o
