# This software is contributed or developed by KYOCERA Corporation.
# (C) 2020 KYOCERA Corporation
#

obj-$(CONFIG_OEM_HKADC)		+= oem-hkadc.o
obj-$(CONFIG_OEM_WIRELESS_CHARGER)		+= oem-wireless-i2c.o
obj-$(CONFIG_OEM_WIRELESS_CHARGER)		+= oem-wireless-charger.o
